
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
      - dashboard

  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    depends_on:
      - backend

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=${MONGO_URL}
      - PASS_SEC=${PASS_SEC}
      - JWT_SEC=${JWT_SEC}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - MPESA_CONSUMER_KEY=${MPESA_CONSUMER_KEY}
      - MPESA_CONSUMER_SECRET=${MPESA_CONSUMER_SECRET}
      - MPESA_SHORTCODE=${MPESA_SHORTCODE}
      - MPESA_PASSKEY=${MPESA_PASSKEY}
    depends_on:
      - mongo

  dashboard:
    build:
      context: ./admin
      dockerfile: Dockerfile
    depends_on:
      - backend

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:



# services:
#   frontend:
#     build:
#       context: ./react-app
#       dockerfile: Dockerfile
#     ports:
#       - "80:80"
#       - "443:443"
#     depends_on:
#       - backend
#     volumes:
#       - /etc/letsencrypt:/etc/letsencrypt:ro
#   backend:
#     build:
#       context: ./api
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     environment:
#       - MONGO_URL=${MONGO_URL}
#       - PASS_SEC=${PASS_SEC}
#       - JWT_SEC=${JWT_SEC}
#       - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
#       - MPESA_CONSUMER_KEY=${MPESA_CONSUMER_KEY}
#       - MPESA_CONSUMER_SECRET=${MPESA_CONSUMER_SECRET}
#       - MPESA_SHORTCODE=${MPESA_SHORTCODE}
#       - MPESA_PASSKEY=${MPESA_PASSKEY}
#     depends_on:
#       - mongo
#   dashboard:
#     build:
#       context: ./admin
#       dockerfile: Dockerfile
#     ports:
#       - "80:80"
#       - "443:443"
#     depends_on:
#       - backend
#     volumes:
#       - /etc/letsencrypt:/etc/letsencrypt:ro
#   mongo:
#     image: mongo:4.4
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
# volumes:
#   mongo-data:




# services:
#   frontend:
#     build:
#       context: ./react-app
#       dockerfile: Dockerfile
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend

#   backend:
#     build:
#       context: ./api
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     environment:
#       - MONGO_URL=${MONGO_URL}
#       - PASS_SEC=${PASS_SEC}
#       - JWT_SEC=${JWT_SEC}
#       - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
#       - MPESA_CONSUMER_KEY=${MPESA_CONSUMER_KEY}
#       - MPESA_CONSUMER_SECRET=${MPESA_CONSUMER_SECRET}
#       - MPESA_SHORTCODE=${MPESA_SHORTCODE}
#       - MPESA_PASSKEY=${MPESA_PASSKEY}
#     depends_on:
#       - mongo

#   dashboard:
#     build:
#       context: ./admin
#       dockerfile: Dockerfile
#     ports:
#       - "4000:80"
#     depends_on:
#       - backend

#   mongo:
#     image: mongo:4.4
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data:
